// lib/supabase.js
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

export const supabase = createClient(eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2ZHVvbnFmenZzYWdocWhxdGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDIwNzYsImV4cCI6MjA3MTg3ODA3Nn0.2dJongqFhUbn1YOQJmmPmvsLtwL7hIEadjsuWQCDcvI, eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2ZHVvbnFmenZzYWdocWhxdGl5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjMwMjA3NiwiZXhwIjoyMDcxODc4MDc2fQ.OQfl4N7upU8AO4Hb60Vc405GYkN3ncSyFpVaO_IImjk)
